# Generated by Django 3.0.7 on 2020-08-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20200824_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pics',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
