# Generated by Django 3.0.7 on 2020-08-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20200824_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='author',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
