# Generated by Django 3.0.7 on 2020-08-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_blog_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
