# Generated by Django 3.0.7 on 2020-08-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_auto_20200827_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_updated',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
