# Generated by Django 3.0.7 on 2020-08-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_blog_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, null=True)),
                ('blog', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.Blog')),
            ],
        ),
    ]
