# Generated by Django 3.0.7 on 2020-08-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_auto_20200827_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='blog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.Blog'),
        ),
    ]
