# Generated by Django 3.0.7 on 2020-08-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_auto_20200827_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
